# Generated by Django 4.0.5 on 2022-07-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='Title Goes Here', max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='all', max_length=255),
        ),
    ]
