# Generated by Django 4.0.5 on 2022-07-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_category_name_category_title_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Title Goes Here', max_length=255),
        ),
    ]
