# Generated by Django 4.0.5 on 2022-07-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Cat Goes here', max_length=255),
        ),
    ]
