# Generated by Django 4.0.5 on 2022-07-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_rename_category_post_prof_category_post_dev_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
